"""init

Revision ID: 90851146add4
Revises: 
Create Date: 2022-10-12 22:41:44.563670

"""
from alembic import op
from sqlalchemy import ForeignKey
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90851146add4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id")
    )

    op.create_table('recipes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('protein', sa.Float()),
        sa.Column('fats', sa.Float()),
        sa.Column('carbohydrates', sa.Float()),
        sa.Column('calories', sa.Float()),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('products',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('protein', sa.Float(), nullable=True),
        sa.Column('fats', sa.Float(), nullable=True),
        sa.Column('carbohydrates', sa.Float(), nullable=True),
        sa.Column('category', sa.Integer, ForeignKey("categories.id")),
        sa.Column('calories', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('recipes_products',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), ForeignKey('products.id')),
        sa.Column('recipe_id', sa.Integer(), ForeignKey('recipes.id')),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###